### PR TITLE
CB-3360: Set custom inappbrowser user agent for ios

### PR DESCRIPTION
**Pull request by cjpearson**
This uses the same OverrideUserAgent and AppendUserAgent properties as the pull requests for cordova-ios and cordova-android.

### CODE REVIEW

**Comment by staugaard** [comment]
Yeah I also need this. :+1:

**Comment by LennardWesterveld** [comment]
:+1:

**Comment by sinofool** [comment]
There is a minor difference with pull request in cordova-ios.
The original OverrideUserAgent will also ignore AppendUserAgent configuration.
If both configs provided, the behaviour will be different.

**Comment by samkelleher** [comment]
One side effect of this is that the main cordova webview will also have its userAgent changed (navigator.appVersion) once at least one instance of InAppBrowser has been created. It seems the userAgent setting will apply to all webviews.

**Comment by jcesarmobile** [comment]
Yeah, on iOS the user agent change applies to all the webviews, maybe it should be restored after closing the inappbrowser

**Comment by willmero** [comment]
This is basically the last thing I need before I am able to push my iOS app version. I would love to see the status of what's happening here

**Comment by Justin-Credible** [comment]
:+1:

**Comment by Quelu** [comment]
Any chances to get this merged ? :smile:

**Comment by shazron** [comment]
This has been merged already. A plugin release is pending: https://github.com/apache/cordova-plugin-inappbrowser/commit/98b63cc37e49466acc9b6b7f027c073fa5313e97

@cjpearson you can close this PR now.

**Comment by Quelu** [comment]
My bad ! Thank you for the information !

**Comment by androdel** [comment]
But where is the fix for iOS?

**Comment by shazron** [comment]
@cjpearson can you rebase this? It can't be pulled in cleanly anymore.

**Comment by cjpearson** [comment]
@shazron, just did a rebase.

**Comment by cordova-qa** [comment]
Cordova CI Build has completed successfully.

**Commit**     - [Link](https://github.com/apache/cordova-plugin-inappbrowser/pull/94/commits/c84daf918dea72cb91c2afc70a267475f77a6519)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-inappbrowser-pr/49/)

| Builder Name  | Console Output | Test Report | Device Logs  |
|     :---:     |     :---:      |   :---:     |     :---:    |
| [Windows 8.1 Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-inappbrowser-pr/49//PLATFORM=windows-8.1-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-inappbrowser-pr/49//PLATFORM=windows-8.1-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-inappbrowser-pr/49//PLATFORM=windows-8.1-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-inappbrowser-pr/49//PLATFORM=windows-8.1-store/artifact/) |
| [Windows 10  Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-inappbrowser-pr/49//PLATFORM=windows-10-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-inappbrowser-pr/49//PLATFORM=windows-10-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-inappbrowser-pr/49//PLATFORM=windows-10-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-inappbrowser-pr/49//PLATFORM=windows-10-store/artifact/) |
| [Windows 8.1 Phone]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-inappbrowser-pr/49//PLATFORM=windows-8.1-phone/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-inappbrowser-pr/49//PLATFORM=windows-8.1-phone/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-inappbrowser-pr/49//PLATFORM=windows-8.1-phone/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-inappbrowser-pr/49//PLATFORM=windows-8.1-phone/artifact/) |
| [iOS]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-inappbrowser-pr/49//PLATFORM=ios/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-inappbrowser-pr/49//PLATFORM=ios/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-inappbrowser-pr/49//PLATFORM=ios/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-inappbrowser-pr/49//PLATFORM=ios/artifact/) |
| [Android]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-inappbrowser-pr/49//PLATFORM=android/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-inappbrowser-pr/49//PLATFORM=android/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-inappbrowser-pr/49//PLATFORM=android/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-inappbrowser-pr/49//PLATFORM=android/artifact/) |

**Pull request closed without merging**
