### PR TITLE
android 增加自定义协议跳转

### PR DESCRIPTION
**Pull request by xingducai**
### Platforms affected
android

### What does this PR do?
inappbrowser 打开第三方网站唤起本地应用失败。调整后如果inappbrowser无法识别的协议，判断是否自定义协议

### What testing has been done on this change?

是的，并且应用已经发布应用市场
### Checklist
- [ ] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [ ] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by infil00p** [comment]
这是否有JIRA问题？ 我正在使用谷歌翻译，但如果你能用英文回应，会让事情变得更快。

**Comment by xingducai** [comment]
thank you for you reply
i think this pull request https://github.com/apache/cordova-plugin-inappbrowser/pull/99  is the same problem that I want to solve.
this is no JIRA  problem. 
in my app ,when i open third party website,
The website has a third-party payment, for example: WeChat payment. When I click the payment button, loaderror captures net::ERR_UNKNOWN_URL_SCHEME and this url is weixin://wap/pay?prepayid , 
For some reason, I do not want to use the _system option, so i have to change the method shouldOverrideUrlLoading() inInAppBrowser.java file to Support for  custom application scheme.

**Comment by infil00p** [comment]
@xingducai Then I think you understand my security concerns listed in the last PR.  You don't exactly want the info going to other intents, right?  Just the payment intent that you intend it to arrive at. We need a JIRA attached to this before it's added it, and it should check the whitelist.  Once it does that, I'm totally cool with adding this feature.

**Comment by infil00p** [comment]
https://issues.apache.org/jira

**Comment by SailingSteve** [comment]
This code starts an activity on the Java side:  ```cordova.getActivity().startActivity(intent)```

Could you provide an example of how the Java side  is handled on the JavaScript side?  What receives and acts on the intent?

**Comment by jcesarmobile** [comment]
A similar PR has been merged, so we will keep that approach and close this PR

**Pull request closed without merging**
