### PR TITLE
breaking: remove UIWebView

### PR DESCRIPTION
**Pull request by jcesarmobile**
Remove all UIWebView code and traces

- Removes all traces of UIWebView from README
- Removes all UIWebView code
- Removes usage of CDVUserAgentUtil as it's being removed from cordova-ios and it's not really needed for WKWebView
- Removes old cordova version code checks as it will only work on the next cordova-ios
- Removes suppressesincrementalrendering and keyboarddisplayrequiresuseraction as they were UIWebView only

### CODE REVIEW

**Comment by NiklasMerz** [comment]
I did some basic tests. Looks good to me 👍

**Comment by jcesarmobile** [comment]
thanks for the reviews!

**Comment by tverilytt** [comment]
Will it be included in next version (3.3.0?)?

**Comment by timbru31** [comment]
Yes, but only in 4.0.0, as this is a breaking change. No ETA though.

**Comment by tverilytt** [comment]
Thanks for that! To use this now then, one has to pull master branch, no npm install option yet?

**Comment by timbru31** [comment]
You can always use the unsupported master branch via git:
`cordova plugin add https://github.com/apache/cordova-plugin-inappbrowser.git`

**Comment by tverilytt** [comment]
@timbru31 Thanks a lot for the tip, thanks to it, App Store deprecation warning related to UIWebView is gone :-)

**Comment by DoctorsInTech** [comment]
Hi Cordova team, my capacitor build is currently being rejected, I think due to the in-app browser still referencing UIWebView. How can I implement the master branch of inappbrowser into my capacitor project?

**Comment by tverilytt** [comment]
@DoctorsInTech Hi! I put this in my package.json:
    "cordova-plugin-inappbrowser": "git+https://github.com/apache/cordova-plugin-inappbrowser.git",
and this in my config.xml:
    <plugin name="cordova-plugin-inappbrowser" spec="git+https://github.com/apache/cordova-plugin-inappbrowser.git" />

Cheers
-jo

**Comment by breautek** [comment]
We generally don't provide any concrete dates for releases due to the volunteer-based nature of the project.

I can confidently say it still may take a little while because I believe there are some PRs we want to include in the 4.0.0 release that still needs to be merged. Then we have to start [Release Process](https://github.com/apache/cordova-coho/blob/master/docs/plugins-release-process.md) which can take some time, especially if there are any rejections.

But you shouldn't **need** to use the unsupported dev version to deal with the `UIWebView` issue. https://github.com/apache/cordova-plugin-inappbrowser/pull/584 was landed in version [3.2.0](https://github.com/apache/cordova-plugin-inappbrowser/blob/master/RELEASENOTES.md#320-jan-04-2020) which makes the plugin respect the [WKWebViewOnly](https://cordova.apache.org/howto/2020/03/18/wkwebviewonly.html) flag, offered in `cordova-ios@5.1.1`.

**Comment by rahul-rajabhoj** [comment]
> @DoctorsInTech Hi! I put this in my package.json:
> "cordova-plugin-inappbrowser": "git+https://github.com/apache/cordova-plugin-inappbrowser.git",
> and this in my config.xml:
> Cheers
> -jo

Can you please specify the change required in config.xml file

**Comment by NiklasMerz** [comment]
Please check this post: https://cordova.apache.org/howto/2020/03/18/wkwebviewonly.html

**Comment by rahul-rajabhoj** [comment]
> Please check this post: https://cordova.apache.org/howto/2020/03/18/wkwebviewonly.html

I am using capacitor along with ionic which uses WKWebView by deafult. Still do I need to follow the mentioned steps ?

**Comment by NiklasMerz** [comment]
We cannot give instructions for using this plugin with Capacitor. You need to ask there or try yourself.

**Comment by rahul-rajabhoj** [comment]
> Hi Cordova team, my capacitor build is currently being rejected, I think due to the in-app browser still referencing UIWebView. How can I implement the master branch of inappbrowser into my capacitor project?
> 
> Nvm I have integrated it, any indication of when 4.0.0 is intended on being released?
> 
> Thanks!

I am also using the InAppBrowser for Azure AD Auth. I followed the following steps to use master branch : 

1. npm install git+https://github.com/apache/cordova-plugin-inappbrowser.git
2. npm install @ionic-native/in-app-browser
3. ionic cap sync

**Comment by rahul-rajabhoj** [comment]
> We cannot give instructions for using this plugin with Capacitor. You need to ask there or try yourself.

Okay Thanks @NiklasMerz . I will use the mentioned steps for one of my ionic cordova application.

**Pull request merged**
