### PR TITLE
chore: bump to next major release 6.0.0

### PR DESCRIPTION
**Pull request by NiklasMerz**
### Motivation and Context

Prepare for next release

See list https://lists.apache.org/thread/p2ycdfv4tf0vnt1dbkv1160o5xz5knns

### Checklist

- [ ] I've run the tests to see all new and existing tests pass
- [ ] I added automated test coverage as appropriate for this change
- [ ] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [ ] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [ ] I've updated the documentation if necessary

### CODE REVIEW

**Review by jcesarmobile — CHANGES_REQUESTED** [review]
In package.json this has to be updated to 7.0.0 or plugin will fail to update
https://github.com/apache/cordova-plugin-inappbrowser/blob/839e2e2f36f838de91d3de69fb08d7192aecd736/package.json#L45

**Comment by NiklasMerz** [comment]
> In package.json this has to be updated to 7.0.0 or plugin will fail to update
> 
> https://github.com/apache/cordova-plugin-inappbrowser/blob/839e2e2f36f838de91d3de69fb08d7192aecd736/package.json#L45

I updated cli & ios to last major release. Is that correct? Android is not needed, yet I guess from the commits in master right?

**Comment by jcesarmobile** [comment]
I don't think we need them to be latest, cordova-ios 6 supports the same iOS versions as cordova-ios 7. And for the CLI I'm not aware of any reason to bump it, maybe because of nodejs support?
A `cordova-android` entry is needed, in geolocation plugin it was set to `>=10.0.0` recently.
https://github.com/apache/cordova-plugin-geolocation/blob/master/package.json#L34-L37

**Comment by NiklasMerz** [comment]
That sounds good to me. I set the same requirements and kept cli from the previous version. Thanks for the help @jcesarmobile. I never really dug into these requirements before.

**Review by jcesarmobile — APPROVED** [review]

**Pull request merged**
