### PR TITLE
CB-10866: Adding engine requirements to package.json

### PR DESCRIPTION
**Pull request by riknoll**
Checked Github to see when the constraint was added (seems like version 0.2.3 8a6bc01814b6d7eb3f605ad47a45d33163153)

### CODE REVIEW

**Comment by riknoll** [comment]
@stevengill that old engine info wasn't doing anything, right? I'm good to remove it?

**Comment by stevengill** [comment]
Yup! It was a early attempt to do what your proposal does. No code checks it.

**Comment by riknoll** [comment]
@rakatyal take a look real quick. The docs for this feature are [here](http://cordova.apache.org/docs/en/latest/guide/hybrid/plugins/index.html#specifying-cordova-dependencies) for reference

**Comment by rakatyal** [comment]
LGTM.

**Pull request closed without merging**
