### PR TITLE
Added option to disable/enable zoom controls

### PR DESCRIPTION
**Pull request by jellekralt**
Hi there,

I've added an option to disable / enable the InAppBrowsers' zoom controls. The option can be passed in the same way the 'location=no' and 'toolbar=no' are passed.

### CODE REVIEW

**Comment by andjo** [comment]
Any particular reason this isn't merged already? Updated documentation perhaps?

It was the second thing after removing the location bar that I wanted to configure after using this plugin for the first time. The zoom controls just looks hideous and like remains of a pre-historic version of Android.

**Comment by jontaylor** [comment]
Please merge this, I need this functionality.

**Comment by Slavrix** [comment]
This functionality would be great if merged please.

**Comment by purplecabbage** [comment]
lgtm!

**Pull request merged**
