### PR TITLE
CB-3360: Set custom inappbrowser user agent for android

### PR DESCRIPTION
**Pull request by cjpearson**
This uses the same OverrideUserAgent and AppendUserAgent properties as the pull requests for cordova-ios and cordova-android.

### CODE REVIEW

**Comment by staugaard** [comment]
Yeah I also need this. :+1:

**Comment by LennardWesterveld** [comment]
:+1:

**Comment by rgo** [comment]
:+1:

**Comment by do-web** [comment]
Readme update is missing!

**Comment by jussihuotari** [comment]
:+1: 

In case someone else wonders: Cordova webview already handles user agent preferences but that doesn't apply when using InAppBrowser. https://github.com/apache/cordova-android/pull/162

**Comment by Justin-Credible** [comment]
:+1:

**Pull request closed without merging**
