### PR TITLE
Cb 13409 - Add more configurable options for toolbar in android and ios

### PR DESCRIPTION
**Pull request by steinaragustli**
### Platforms affected
Android, iOS

### What does this PR do?
See https://issues.apache.org/jira/browse/CB-13409

### What testing has been done on this change?
I have tested the combinations possible with the new available configurations and have found them working fine, see in screenshots in the link on jira. These changes shouldn't break anything since they only allow new options.

### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [x] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by janpio** [comment]
Why all these Boolean => String changes?

**Comment by steinaragustli** [comment]
Well, currently the additional options that are supported for android, are only binary options. To be able to support options that aren't boolean, the hashmap needs to be <String, String>.

**Comment by steinaragustli** [comment]
This is ready, are you going to review this @janpio or someone else ?

**Comment by janpio** [comment]
Too much code for me to say if this actually works (not being an Android and iOS developer...). You might want to comment on the initial issue again that this PR is read for review.

**Comment by dpa99c** [comment]
@steinaragustli these changes look good to me: they add some useful options. 

Is there some official review process this needs to go through to get merged? Because I've looked at your code changes and they look solid: the change of the HashMap from `<String, Boolean>` to `<String, String>` makes complete sense to enable specification of non-boolean options.

**Comment by janpio** [comment]
> Is there some official review process this needs to go through to get merged? 

"Review process" is the wrong word, but I was told (I'm quite new in the Cordova PMC, so I didn't know before...) as this is a "new feature" or "new functionality", it would be great if @steinaragustli could send a short email to the [Dev Mailnig List](https://cordova.apache.org/contact/) and explain the changes a bit. 

(Background: As Cordova is an Apache project, [discussion should/has to happen on mailing lists](http://apache.org/foundation/mailinglists.html).)

**Comment by dpa99c** [comment]
@steinaragustli I've extended your PR in [a fork](https://github.com/dpa99c/cordova-plugin-themeablebrowser/tree/CB-13409) to [add support to Android for a footer close button similar to the iOS "Done" button](https://github.com/dpa99c/cordova-plugin-themeablebrowser/commit/abffd004ee4240c1c25adc060633027405faa788).

Once your PR is merged, I'll create a JIRA issue and submit this as a separate PR.

Here's some screenshots with the relevant options:

`location=yes,footer=yes`


`location=no,footer=yes`


`location=yes,footer=yes,closebuttoncaption=Done`


`location=yes,footer=yes,closebuttoncaption=Done`


`location=no,footer=yes,closebuttoncaption=Done,closebuttoncolor=#0000ff`


`location=no,footer=yes,footercolor=#0000ff,closebuttoncaption=Done`


`location=no,footer=yes,footercolor=#00ff00,closebuttoncaption=Done,closebuttoncolor=#0000ff`


`location=no,footer=yes,footercolor=#CC000000,closebuttoncaption=Done,closebuttoncolor=#00FFFF`

**Comment by janpio** [comment]
@steinaragustli Could you also rebase your PR so it gets the latest commits, one of them was to fix the Travis builds and would be needed for your PR to have green tests.

**Comment by steinaragustli** [comment]
Yes i will fix the travis build and do what you talked about regarding the code review, and then let you know.

**Comment by janpio** [comment]
That worked, thanks.
(Now Appveyor is stuck in "queued", but maybe waiting a few more hours fixes that. Otherwise I think we can ignore that)

**Comment by steinaragustli** [comment]
Yes, so now just wait until someone can review ?

**Comment by janpio** [comment]
Yes.

**Comment by erl4nc** [comment]
Any plan to merge this?  This PR provides great UI customization options.  I was using [ThemeableBrowser](https://github.com/initialxy/cordova-plugin-themeablebrowser) to tweak UI.  Unfortunately, it is no longer maintained.  This could be a viable replacement.

**Comment by steinaragustli** [comment]
I requested a review, i havent heard anything.

**Comment by dpa99c** [comment]
@stevengill @agrieve @shazron @purplecabbage @jcesarmobile are any of you guys able to review/approve this PR? It contains very useful functionality but has been open almost 3 months...

**Comment by purplecabbage** [comment]
LGTM! @infil00p ?

**Comment by infil00p** [comment]
Is there a docs PR that corresponds with this? This is a pretty big API change.

**Comment by janpio** [comment]
`README.md` is updated (with the added options), which is used to generated the docs at https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-inappbrowser/

**Comment by andaofei** [comment]
On Android, when setting footer to yes, the footer bar overlaps the WebView content, causing it to cover up the bottom slice of the WebView.

**Comment by andaofei** [comment]
image

**Comment by janpio** [comment]
@andaofei Please create a new issue for this problem. This will be ignored here.

**Pull request merged**
