### PR TITLE
commented closedialog at the end

### PR DESCRIPTION
**Pull request by mrshetab**
### Checklist

- [x] I've run the tests to see all new and existing tests pass
- [x] I added automated test coverage as appropriate for this change
- [x] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [x] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [x] I've updated the documentation if necessary

### CODE REVIEW

**Comment by purplecabbage** [comment]
Commenting out code is never a solution.  What is this for? What issue are you trying to resolve?

**Comment by mrshetab** [comment]
I used this plugin in my application, but when the user presses the hardware back button while being on the first page, this will cause the browser to get closed and not minimizing the whole app. I want the app to be minimized instead of closing the app browser.

**Comment by purplecabbage** [comment]
Your change would force every app that uses this plugin to behave how you want your own app to behave.  You should look at changing this in your own app.

The android option 'hardwareback' might do what you want.

**Comment by mrshetab** [comment]
Oh ok! But I have two problems.
1- hardwareback won't do the thing.
2- I use "phonegap build" to build my app and "phonegap build" would only use plugins from github and I can not download the code, implement my changes in the code and then use it as my special plugin.

**Comment by purplecabbage** [comment]
PhoneGap Build CAN build any plugin published to NPM or any github repo.
Just publish your own version ( with your own name for it ... ) and you can use it with pgb.

I would however advise looking at doing some/most of this in your app.
There are ways to intercept the back button in cordova-android, and you could also detect the condition that you want to exit on ... without knowing your specific goal I cannot tell you exactly how you would accomplish it.

**Comment by mrshetab** [comment]
Oh ok, Thank you very much

**Pull request closed without merging**
