### PR TITLE
(ios): remove UIWebView code

### PR DESCRIPTION
**Pull request by jcesarmobile**
Breaking change!
Do not merge yet

### Platforms affected
iOS

### Motivation and Context

Closes https://github.com/apache/cordova-plugin-inappbrowser/issues/532
Apple is warning about deprecate API usage because of UIWebView ussage, this PR removes all UIWebView code

### Description
Apple is warning about deprecate API usage because of UIWebView ussage, this PR removes all UIWebView code

### Checklist

- [ ] I've run the tests to see all new and existing tests pass
- [ ] I added automated test coverage as appropriate for this change
- [ ] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [x] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [ ] I've updated the documentation if necessary

### CODE REVIEW

**Comment by B4RteQPl** [comment]
Any updates?

**Comment by jcesarmobile** [comment]
It's still not decided if we are going to remove the whole code or if we will hide it behind compile flags for now, so can't be merged yet.

See https://github.com/apache/cordova-discuss/pull/110

**Comment by hdung912** [comment]
Hi @jcesarmobile after i install force jcesarmobile:remove-uiwebview-apache also using bpresles:master (https://github.com/apache/cordova-ios/pull/663) i have issues 'Cordova/CDVUIWebViewDelegate.h' not found reason in pull&request 663 Cordova-ios did remove it, how can i fix it? Do you have any idea on it.

**Comment by dpa99c** [comment]
If we do decide to remove UIWebView code entirely, we may as well remove the shim which switches between UIWebView vs WKWebView implementations provided by `CDVInAppBrowser.h/.m`.
We can then rename `CDVWKInAppBrowser` => `CDVInAppBrowser` and remove `usewkwebview` from code and documentation.

**Comment by jcesarmobile** [comment]
going to close since it's full of conflicts now, might send a new PR in the future removing the recently added compiler flags

**Pull request closed without merging**
