### PR TITLE
added cookies support for Android and iOS

### PR DESCRIPTION
**Pull request by denisx304**
### Platforms affected
Android
iOS

### What does this PR do?
Allows the `cordova.InAppBrowser.open()` function to receive another parameter, `cookies`, an object described like `name: value`. It sets then those cookies through Android and iOS native code.

### What testing has been done on this change?
`cordova.InAppBrowser.open(page, "_self", null, { "cookieName": "cookieValue" });`
The cookies were verified on the server-side.

### Checklist
- [ ] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [ ] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by danova123** [comment]
Does it also reads the cookie value?

**Comment by denisx304** [comment]
@danova123 what do you mean?

**Comment by danova123** [comment]
@denisx304 I meant does it return cookies from server when user logs in( For example)
will CookieManager.getCookie be called at any point of time or could it be called manually?

**Comment by denisx304** [comment]
@danova123 Please go through my commit. The `cordova.InAppBrowser.open` receives one more parameter, which is an object. The keys of this object are the name of the cookies that you want to set, and the values are the values of the cookies.

It simply sets these cookies with `CookieManager.setCookie` to the domain where the url belongs.

Did my comment answer your question?

**Comment by danova123** [comment]
I mean its a great addition to the existing plugin. I will use it to set cookies( Name and Value) but i need to read cookies first from a different browser to pass it to the next one. I will be using it for Cookie Based Authentication, where i receive a session cookie from user login and i will pass the same cookie to access api data from the same domain. Do you have plans of calling getCookie method where user can pass the cookie name and inappbrowser will return the cookie value.

**Comment by denisx304** [comment]
I understand you now. This PR does not include that feature.

**Comment by danova123** [comment]
@denisx304 Thanks for the clarification. Looking forward to see it getting added to the base branch soon.

**Comment by janpio** [comment]
@denisx304 Does this PR enable me to set random cookies for e.g. google.com when opening InAppBrowser to open google.com?

**Comment by denisx304** [comment]
@janpio You can send any cookie as long as the server interprets it.

**Comment by janpio** [comment]
You are right, this is equivalent to messing with the local cookies with the developer tools of your browser.

**Comment by denisx304** [comment]
exactly

**Comment by janpio** [comment]
May I asked what is a use case for this? What problem does this solve?

**Comment by denisx304** [comment]
Whenever you want to send cookies to one url.
For exemple keeping the user logged in from your mobile application to the web application.

**Comment by thesourav123** [comment]
@denisx304 i am facing an issue with the original inappbrowser not saving session cookies when app is closed in iOS(But, works in Android). Will this merge fix my issue.

**Comment by thesourav123** [comment]
This was needed. Finally, thanks a lot. i tested and it works. Yay!!

**Comment by jourdanrodrigues** [comment]
+1

**Comment by brunobc182** [comment]
+1 please!

**Comment by piggyslasher** [comment]
What is going on? Can someone follow up on the proposed merge?

**Comment by robinvalk** [comment]
Awesome feature!

**Comment by janpio** [comment]
Hey, to move this forward @denisx304 we will probably have to give this a little push. I don't know enough about Android to review this myself.

In general, code and feature additions should be announced on the [dev mailing list](http://cordova.apache.org/contact/) with request for comments and more important code reviews and later merge.

**Comment by gatelli** [comment]
It’s a very good new to implement that ! Do you have a release date for add this in trunk ?

**Comment by infil00p** [comment]
The conflcits and the eslint errors need to be fixed before we can evaluate and accept this.  There also needs to be a JIRA issue attached to this.

**Comment by robinvalk** [comment]
@denisx304 Could you tell us why you closed this issue? Too much of a hassle?

**Comment by jourdanrodrigues** [comment]
@denisx304 What happened? I remember only code formatting was missing to pass the tests. :/

**Comment by denisx304** [comment]
I started the PR when my fork had only "cookies support", but now my branch includes other commits related to a specific application that I am building, which should be ignored.

**Comment by Drezounet** [comment]
so ?

**Comment by brodybits** [comment]
Considering that this PR is closed I would not expect any more work or
meaningful discussion here. In case of interest I suggest you make the
request to: dev@cordova.apache.org

**Pull request closed without merging**
