### PR TITLE
CB-3750: Add loading spinner for ios

### PR DESCRIPTION
**Pull request by cjpearson**

### CODE REVIEW

**Comment by syndbg** [comment]
I suggest that this is a bit more flexible.

Don't force the color and spinner to be always visible.

Instead introduce two options ex. `spinnerColor` and `spinnerHidden`

**Comment by sgrebnov** [comment]
Tested and merged

**Comment by ozeranjo** [comment]
The ability to pass options for overriding the spinnerColor and hiding the spinner were not included as part of the commit above. Can this be considered for a future release? A valid use case exists if a custom loading progress bar is used -- showing the standard activity indicator can be duplicative and visually confusing.

**Comment by karlachavez** [comment]
Hi guys,

I'm agree with @ozeranjo. At least a hide spinner feature is needed in order to avoid redundance on the site if it already has a custom activity indicator. Is there any plan to include is soon?

**Comment by shazron** [comment]
Please file feature request issues for the needed features at issues.cordova.io
Thanks!

**Comment by NiklasMerz** [comment]
For hide spinner see #254 and [CB-13659](https://issues.apache.org/jira/browse/CB-13659)

**Pull request closed without merging**
