### PR TITLE
CB-12969 android: Added support for data URIs

### PR DESCRIPTION
**Pull request by matrosov-nikita**
### Platforms affected
Android

### What does this PR do?
Adds support for data Uri (e.g. `'data:text/html, <html><body><h1>Hello</h1></body></html>'`)

### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by filmaj** [comment]
Is this supported on any platforms other than iOS?

**Comment by matrosov-nikita** [comment]
Seems that it's supported on browser platform only (for now I've verified for android, windows, ios, browser platforms). I've updated PR to add support for windows platform.
@filmaj, should I check all platforms from this list: https://github.com/apache/cordova-plugin-inappbrowser#supported-platforms?

**Comment by filmaj** [comment]
The reason I ask is I am wondering if / how the documentation or the API reference for this plugin would change as a result.

And I wouldn't test against all those platforms, I personally test against Android, iOS, Windows and Browser.

**Comment by matrosov-nikita** [comment]
@filmaj, I would expand this section (https://github.com/apache/cordova-plugin-inappbrowser#more-usage-info) by adding samples with Data URIs.

But, for now, I found that this patch doesn't work on windows with data URI in case of using `_blank` target. Not sure, whether it supposed to work.

**Comment by filmaj** [comment]
Ideally this kind of stuff lands across all major platforms in Cordova.

Generally, if something is not doable due to platform-specific restrictions, we, at the minimum, document it (via "Quirks" in our docs).

I think it's a judgment call by you. If it's not possible to do on Windows, or the implementation is very hard and would take long, then perhaps it is worth skipping one platform implementation.

**Comment by matrosov-nikita** [comment]
@filmaj, I've added a section in docs for Data URIs, could you please take a look?

**Comment by filmaj** [comment]
Hey, i'm on vacation for the next couple of weeks (getting married!). CAN
you get someone else to review? Perhaps @stevesgill

On Aug 15, 2017 11:50 AM, "Nikita Matrosov" <notifications@github.com>
wrote:

@filmaj <https://github.com/filmaj>, I've added a section in docs for Data
URIs, could you please take a look?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/apache/cordova-plugin-inappbrowser/pull/227#issuecomment-322427086>,
or mute the thread

**Comment by matrosov-nikita** [comment]
@filmaj, sure, my congratulations :)
@stevengill, could you please take a look?

**Comment by infil00p** [comment]
Why is there a conflict in windows/InAppBrowserProxy.js? That needs to be fixed before getting merged in.

**Comment by infil00p** [comment]
It looks like the PR got borked, and we can't accept it as is due to the conflict.,  Closing.

**Comment by jjtfsalgado** [comment]
I'm still getting this issue. Is there any workaround?

**Pull request closed without merging**
