### PR TITLE
Cb 13969 - Allow close button and navigation buttons positions to be swapped

### PR DESCRIPTION
**Pull request by steinaragustli**
### Platforms affected
iOS and Android

### What does this PR do?
Enables the position of the close/done button on inappbrowser to be swapped with the position of the navigation buttons. See https://issues.apache.org/jira/browse/CB-13969 for screenshots.

### What testing has been done on this change?
I have tested all possible combination of parameters when different buttons are hidden and shown. So everything is consistent with how this should work.

### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [x] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by dpa99c** [comment]
I notice this is only implemented for the UIWebView variant of InappBrowser on iOS - can it be extended to the WKWebView variant as well?

**Comment by steinaragustli** [comment]
> I notice this is only implemented for the UIWebView variant of InappBrowser on iOS - can it be extended to the WKWebView variant as well?

@dpa99c  I will try that. I will let you know.

**Comment by steinaragustli** [comment]
> > I notice this is only implemented for the UIWebView variant of InappBrowser on iOS - can it be extended to the WKWebView variant as well?
> 
> @dpa99c I will try that. I will let you know.

@dpa99c This is now extended to WKWebView, so on my part its good to go.

**Comment by steinaragustli** [comment]
@stevengill @agrieve @shazron @purplecabbage @jcesarmobile

Is anyone able to review this ? It's a old pull request which i just updated. It's not a big change but enables some desirable additional functionality.

**Comment by purplecabbage** [comment]
Looks good.  I'll have to test this before merging but I'll try to get to it this week.

**Comment by steinaragustli** [comment]
> Looks good. I'll have to test this before merging but I'll try to get to it this week.

Ok awesome, thank you.

**Pull request merged**
