### PR TITLE
CB-12975: (docs) Resort and reword cordova.InAppBrowser.open `options` lists

### PR DESCRIPTION
**Pull request by janpio**
### Platforms affected
n/a, only docs changes

### What does this PR do?
Resort and reword cordova.InAppBrowser.open `options` lists for better developer experience. More reasoning at https://issues.apache.org/jira/browse/CB-12975

### What testing has been done on this change?
n/a

### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- n/a Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by janpio** [comment]
Sure!

Well, if you tell me roughly how to do that. Some pointers would be nice, never have done something like that. Can I actually do that on Github?

**Comment by filmaj** [comment]
Hah! I haven't used GitHub UI to do this kinda stuff before, so I can only tell you how to do it via the `git` command line tool.

By "rebase," I meant ensuring that the latest changes from this repository are included in your patch. Right now, this PR is a couple of changes behind.

As for squashing commits / changing the commit message, I think if you re-do your edits, that should end up being the same thing. Feel free to close this pull request and open a new one.

I just want to ensure that:
a) There is only commit containing these changes and
b) The commit message is prefixed with the CB-12975 key

thanks again!

**Comment by janpio** [comment]
Yeah, I totally get that.

Can you actually post the `git` commands you would use? Then I can use this as my googling starting point. Wanted to learn that for quite some time, but always found an alternative (like redoing the changes in a new PR... lazy...)

**Comment by filmaj** [comment]
Sure! No problem.

First you'd need to clone the repository down to your machine, giving you a local copy to work with. You already have your own fork of the repository (https://github.com/janpio/cordova-plugin-inappbrowser), so you can clone that down:

```
 > git clone https://github.com/janpio/cordova-plugin-inappbrowser.git
```

Move into the directory you just cloned down:

```
 > cd cordova-plugin-inappbrowser
```

You'll want to ensure you have all of your various branches and the latest pulled down from your fork. Do that with the `fetch` command, specifying `origin` as what you want to fetch. When you cloned the repository with the `git clone` command, `git` automatically sets the origin "location" (or "remote" in gitspeak) to the URL you originally cloned from.

```
 > git fetch origin
```

According to the top of this PR, your changes are located in a branch of your fork called `patch-1`. So, let's checkout this branch:

```
 > git checkout patch-1
```

Now you should see your changes when you go look at the README.

Cool. Next, we will add a remote representing the Apache repository, so that you can pull down the latest changes from the Apache repository:

```
 > git remote add apache https://github.com/apache/cordova-plugin-inappbrowser.git
```

Then, like we did for your fork, you'll want to pull the latest changes from the Apache remote:

```
 > git fetch apache
```

OK, we're getting closer. Rebasing essentially "synchronizes" changes between two different branches of code. So, we'll want to have your `patch-1` branch available, as well as the `master` branch _from the Apache remote_. This is a little tricky, but I can guide you through it:

```
 > git checkout -b apache-master remotes/apache/master
```

The above is saying, checkout a _new_ branch called `apache-master` (`-b apache-master`), and have this branch _track_ the `master` branch from the `apache` remote. Hope that makes sense and you are following along.

OK, almost there. Next we need to go back to your `patch-1` branch to begin the rebase:

```
 > git checkout patch-1
```

Finally, we initiate the rebase between your `patch-1` branch and the apache `master` branch like this:

```
 > git rebase -i apache-master
```

This will bring up an interactive console / text editor where you should be shown a chronologically ordered list of your commits. Any line that starts with a `#` is a comment and can be ignored - but read through them as it gives you instructions on how to do rebasing. The other lines represent your individual commits, and the first word in each line represents how you want to modify the commits. What you will want to do is "squash" your last commit by changing the first word in front of that commit to "squash". Then save and exit the text editor. You will be presented with one more screen in a new text editing window. This last screen will give you a chance to modify the commit message for your new two-commits-squashed-into-one-commit reality. This is where I would love if you would be able to prefix your commit message with "CB-12975" :)

I highly suggest reading thess article about rebasing "interactively": 
- http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html
- https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history#interactive-rebase

Good luck! If you have any more questions, just ping me.

**Comment by janpio** [comment]
Thanks for the proper explanation! I almost understood it and went to work with Sourcetree...

https://www.atlassian.com/blog/sourcetree/interactive-rebase-sourcetree explains that interactive rebase is also possible with Sourcetree. But of course I couldn't rebase at the beginning because I was working on my fork which is not really connected to the apache repo any more.

So I did as you said and added the apache repo again (while having checked out `patch-1`. This created this nice merge commit automatically: https://github.com/janpio/cordova-plugin-inappbrowser/commit/3066febdc723c5d0d99ab458c92038fa2f064553 This seems to be what we wanted to "rebase" my commits, because now "This branch is 3 commits ahead of apache:master. "

Via the "interactive rebase" feature of Sourcetree I could now "merge" my initial commit and the whitespace commit. But then I somehow messed up, because now the commits from the merge commit are in my branch as well, additionally to that dumb merge commit in the first place...

Well, I have to investigate a bit more it seems ;)

**Comment by janpio** [comment]
As a first "recovery" I branched after my now rewritten commit into patch-1b and created a pull request from there at #234. This seems to have worked and almost looked as it should. If I find no way to repair this PR, we can just merge that one.

**Comment by janpio** [comment]
Yeah no, I have no idea what actually happened and why and how I could undo it :/
So if you @filmaj are ok with it, let's just go with #234.

**Comment by filmaj** [comment]
Sounds good, I'll check that out. Thanks for taking that on!

> because now "This branch is 3 commits ahead of apache:master. "

☝️ that's what you want!

**Comment by filmaj** [comment]
@janpio I have merged in your changes to master, see 7611645469aa4f9a4b0ebeb826317030cc2900a2.

Can you close this pull request?

**Pull request closed without merging**
