### PR TITLE
[WIP] Add top notch detection

### LINKED ISSUE #301: Issue with status bar on iPhone X when toolbar is at the top (v3.0.0)
There is an issue with the status bar and the iPhone X as described at http://www.doroja.com/smartdic.aspx?decode=1&url=aHR0cHM6Ly9zdGFja292ZXJmbG93LmNvbS9xdWVzdGlvbnMvNDczOTk5MzgvaXNzdWUtd2l0aC1zdGF0dXMtYmFyLXVzaW5nLWNvcmRvdmEtaW5hcHBicm93c2VyLWFuZC1pb3MtMTEtYW5kLWlwaG9uZS14B64Coded!

When the inappbrowser toolbar is at the top of the screen, the status bar on the iPhone X is half white and half gray.

Changing the following line in CDVInAppBrowser.m solves the problem and makes the whole status bar gray.  Change line:
`statusBarFrame.size.height = STATUSBAR_HEIGHT;`
to
`statusBarFrame.size.height = 0;`

This does not seem to negatively affect other iPhones or iPads.

### PR DESCRIPTION
**Pull request by NiklasMerz**
### Platforms affected
iOS

### Motivation and Context

This fixes an issue with iPhone that have a notch.

Closes #301 

### Description

Detect if phone has notch and adjust statusbar.

### Testing

Using with iPhones with notch and without. Deployed to production app for some time.

### Checklist

- [x] I've run the tests to see all new and existing tests pass
- [x] I added automated test coverage as appropriate for this change
- [x] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [x] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [x] I've updated the documentation if necessary

### CODE REVIEW

**Comment by NiklasMerz** [comment]
@dpa99c Sorry for the ping and thanks for your reviews on my PRs, but I would like to add you as a reviewer. Probably someone should create a CODEROWNERS file with you, because you review PRs in this repo anyway :-D

**Comment by dpa99c** [comment]
Will try to get around to it shortly

**Comment by dpa99c** [comment]
@NiklasMerz Sorry for the delay. I've tested your branch used my [test harness project](https://github.com/dpa99c/cordova-plugin-inappbrowser-test).

It works fine if the IAB is opened while the device is in portrait orientation:


But if you orientate the device into landscape orientation before opening the IAB, the status bar height is incorrect in the IAB when it is opened. Instead of displaying no status bar, there's grey bar:


This then persists if you rotate the device back to portrait orientation:

**Comment by dpa99c** [comment]
```ob

**Comment by NiklasMerz** [comment]
Thanks for your review. I never use portrait mode So forgot to test this.

I will get to this tomorrow and test your code.

**Comment by jcesarmobile** [comment]
This is not a proper fix, it just hides the fake status bar for iPhone X and other devices with notches.

The proper fix should make the fake statusbar the size of the notch to be consistent, or just remove the fake statusbar for all devices.

**Comment by NiklasMerz** [comment]
You are right. What about removing the statusbar for all devices? I think that would make sense. Does this mean we need an option to for showing/hiding the statusbar?

**Comment by jcesarmobile** [comment]
I personally vote for removing it, it’s an ugly “hack” that doesn’t work well

**Comment by dpa99c** [comment]
> I personally vote for removing it, it’s an ugly “hack” that doesn’t work well

I agree. Considering the effort required to make the statusbar work properly in the IAB for devices with a notch, removing it entirely is much easier and since the IAB is a secondary UI to the main Cordova app UI, not displaying the statusbar while it's open seems like a not-too-big inconvenience.

We could at least start by removing it entirely and if someone has time to make a PR which fixes display of the statusbar on all devices (notch and non-notch) in all orientations, with the additional option to display or not display it, then we can consider re-adding it at that point in time.

**Comment by jcesarmobile** [comment]
Making it configurable is going to be troublesome as the toolbar is created in the CDVInAppBrowserNavigationController, where the InAppBrowser options are not available

**Comment by mosababubakr** [comment]
Hello guys,

You can take SAFARI browser as an example, 
If you try to show safari in landscape mode, you will see that the status bar is hidden in landscape mode. (Iphone x family)

So, i think that inappbrowser could be better, if it appear as safari browser for ios devices layout.

And also, safari browser set safe margins by default in both portrait and landscape modes, thus,  inappbrowser should be in same strategy, because we can’t control other external website links that opened in inappbrowser.
(We cannot control the css of the layout for the external links).

So, please take a look by trying to open any url for example: youtube.com in safari browser for both landscape and portrait, and you will notice the default safe margin which was set by apple developers for safari browser app.

Hope this help.

Regards

**Comment by mosababubakr** [comment]
Removing status bar in portrait mode not good idea.

Please take a look into safari browser in both portrait and landscape modes by trying to open any website, you will see that the status bar appear in correct height in portrait mode, and it hidden in landscape mode, taking into account that safe margins was set in landscape mode (left and right of the screen edges).

**Comment by mosababubakr** [comment]
Take safari browser as an example:

———For iphone x family devices———
portrait mode:
Inappbrowser could be look better if the status bar appear in correct height with safe margin-top.

landscape mode:
Inappbrowser could be better if status bar is hidden, taking into account that safe margin edges (left and right) should be set in correct sizes as safari.

————

———older versions of iphone devices——
the status bar should appear in both modes (portrait and landscape) as safari app do.

**Comment by mosababubakr** [comment]
Removing the status bar is not good idea and not solve this issue.

Lets take safari browser app as a good example here: 

———For iphone x family devices———
portrait mode:
Inappbrowser could be look better if the status bar appear in correct height with safe margin-top.

landscape mode:
Inappbrowser could be better if status bar is hidden, taking into account that safe margin edges (left and right) should be set in correct sizes as safari.

————

———older versions of iphone devices——
the status bar should appear in both modes (portrait and landscape) as safari app do.

**Comment by mosababubakr** [comment]
Removing the status bar not good idea, not solve this issue, and not the optimal solution.

Lets take safari browser app as a good example here, by trying to open any website.
For any iphone device, you will see that:

portrait mode:
the status bar appear in correct height with safe margin-top.

landscape mode:
The status bar is hidden.
taking into account that safe margin edges (left and right) was set in correct margin-sizes for iphone x family devices.

**Comment by mosababubakr** [comment]
@NiklasMerz  @dpa99c 
Removing the status bar is not a good idea, not solve the issue, and not the optimal solution.

Let's take SAFARI BROWSER APP as a good example here.

Please try to  to open any website, for e.g.: githubb.com, in any iPhone device, you will see that:

---PORTRAIT MODE---
The status bar appear in correct height with safe area in the top.

---LANDSCAPE MODE---
The status bar is hidden.

Taking into account that safe margin area (the left and the right) was set for iphone x family devices or greater in landscape mode.

*** SAFARI BROWSER APP vs. INAPPBROWSER PLUGIN ***

---PORTRAIT MODE---



--------------------
--- LANDSCAPE MODE---

**Comment by jcesarmobile** [comment]
we are talking about the toolbar that is used as a fake status bar, not the real status bar, the status bar won't be hidden, but apple removed what used to be the solid status bar on iOS 7, so trying to keep that appearance of the iOS <= 6 status bar makes no sense anymore

**Comment by mosababubakr** [comment]
> we are talking about the toolbar that is used as a fake status bar, not the real status bar, the status bar won't be hidden, but apple removed what used to be the solid status bar on iOS 7, so trying to keep that appearance of the iOS <= 6 status bar makes no sense anymore

@jcesarmobile 
If you need to understand what i mean, please try to open any website (ANY WEBSITE) with :

- inappbrowser (for landscape and portrait modes).

- Safari Browser app (landscape and portrait modes).

And you will see that safari layout margins looks great in iphone x family devices.
But with inappbrowser, there were 2 issues:
first: in the portrait mode, there a is gray bar (show the time and the signal of cellular.. etc) that conflict with the top of the page.
second: in the landscape mode, there is a gray empty bar that make the view is an ugly.

regards

**Comment by jcesarmobile** [comment]
I understand, looks like you don’t.
You said that removing the status bar was not the solution, I told you we weren’t talking about the real status bar, but the fake status bar.
Now you say that InAppBrowser has ugly gray bars and that’s an issue.
That’s the fake status bar we are talking about and we are saying we should remove.

So you seem to agree with us

**Comment by mosababubakr** [comment]
@jcesarmobile 
Yes i agree with you all, that this need to remove to make inappbrowser appearance well.

regards

**Comment by mosababubakr** [comment]
@NiklasMerz 

any new update ?

**Comment by jcesarmobile** [comment]
Please, don’t try to rush things, we are all volunteers and we do what we can when we can and for free. Feel free to send the pull request yourself if you need it so much.

**Comment by mosababubakr** [comment]
> Please, don’t try to rush things, we are all volunteers and we do what we can when we can and for free. Feel free to send the pull request yourself if you need it so much.

I know that @jcesarmobile .

But i ask him if he has a new update for this issue.

This general improvements for this plugin to help all users not only me.

Regards

**Comment by NiklasMerz** [comment]
I'm with @jcesarmobile . You need to be patient or do the fix yourself. That's how I do things. That's how it works in Open Source. We cannot expect anyone to do the work just because we feel the need for us and others.

I am currently happy with the solution as it is in this PR. I may do the complete removal of the statusbar some time in the future if I have the spare time, but let's see.

@mosababubakr Just try doing this change yourself. It is not that hard as you might expect. I never worked on native iOS projects before, but I did some contributions to iOS Cordova plugins just by trying stuff out and googling. You may find a solution and can get feedback on a PR to get it working as you like.

**Comment by mosababubakr** [comment]
Thanks for helping

And we are sorry for the inconvenience.

Just i made those comments to ensure this plugin appear in good situation because it is an important plugin.

Regards

**Comment by brodybits** [comment]
Hi @NiklasMerz I took the liberty to add "[WIP]" to the title since this PR seems to be not ready for us to review and merge right now. (I would really favor  I would also wonder if this might be solved by https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller or by the https://github.com/toontoet/cordova-plugin-themeablebrowser fork that was mentioned in <https://github.com/apache/cordova-plugin-inappbrowser/issues/301#issuecomment-433031190>?

I would also favor getting rid of the status bar, let other forks do something more elaborate if needed.

**Comment by NiklasMerz** [comment]
That's fine. I can try to do the removal of the fake statusbar, if I find time anytime soon, to update this PR. Removing the statusbar seems logical.

**Comment by mosabab** [comment]
> That's fine. I can try to do the removal of the fake statusbar, if I find time anytime soon, to update this PR. Removing the statusbar seems logical.

You are right, 

I test your fork modified plugin, and work well in portrait mode, but in landscape mode the empty grey bar appear, I think removing it could be better.

**Comment by mosabab** [comment]
@NiklasMerz 
When you think this pull could be done ?

**Comment by NiklasMerz** [comment]
No **this one is not ready**. It works for me and might work for you but it is not a proper fix and won't be in 3.2.0

Like suggested by jcesarmobile a proper fix would be to remove the "fake statusbar" completely in the next major release. I looked at this briefly and I am afraid I don't know enough about Objective-C to do this in the time I have available. I created #604 for that and others might pick this up.

**Comment by justjoeyuk** [comment]
@jcesarmobile I'm using Ionic 4 and Capacitor (I know this is specific to in-app-browser). However, is there anyway I can use the in-app-browser Cordova plugin with my own custom changes in Capacitor? Can't find any way to do that.

**Comment by brodybits** [comment]
@justjoeyuk and others please feel free to fork and adapt.

**Comment by sardapv** [comment]
I did little change in plugin to detect and Resize InAppBrowser based on Notched devices. It adjusts its dimensions to fit safe area with orientation change as well . PS: I am not a swift or Pro apple coder, but took lot of time to get it fixed for my use case. Any contributor is free to modify below code, might be ugly. Have not tested this with that Done button pane for IAB, for my use case of hybird app which uses full screen no URL bar, this worked.

**Change in CDVInAppBrowserNavigationController.m**

`statusBarFrame.size.height = 0;`

**Change in CDVWKInAppBrowser.m**

**declare -**
```
float orgHeight = 0;
float orgWidth = 0;
```
**add these 2 methods-**

```
- (BOOL)hasTopNotch { // method returns true if notch is at top
    if (@available(iOS 11.0, *)) {
        if([[[UIApplication sharedApplication] delegate] window].safeAreaInsets.top>20.0){
            return YES;
        }
    }
    return  NO;
}

- (BOOL)hasLeftOrRightNotch { //method returns true if notch is at left or right side
    if (@available(iOS 11.0, *)) {
        if([[[UIApplication sharedApplication] delegate] window].safeAreaInsets.left>20.0){
            return YES;
        }
        if([[[UIApplication sharedApplication] delegate] window].safeAreaInsets.right>20.0){
            return YES;
        }
    }
    return  NO;
}
```
**Modify ViewWillAppear to** 
```
- (void)viewWillAppear:(BOOL)animated

{
    if (IsAtLeastiOSVersion(@"7.0") && !viewRenderedAtLeastOnce) { // set origin based on notch and safe area
        viewRenderedAtLeastOnce = TRUE;
        CGRect viewBounds = [self.webView bounds];
        if ([self hasTopNotch]) {
            float topSafeArea = [[[UIApplication sharedApplication] delegate] window].safeAreaInsets.top;
            viewBounds.origin.y = topSafeArea;
        } else if ([self hasLeftOrRightNotch]) {
            float leftSafeArea = [[[UIApplication sharedApplication] delegate] window].safeAreaInsets.left;
            viewBounds.origin.x = leftSafeArea;
        } else {
            viewBounds.origin.y = STATUSBAR_HEIGHT;
            viewBounds.size.height = viewBounds.size.height - STATUSBAR_HEIGHT;
        }
        self.webView.frame = viewBounds;
        [[UIApplication sharedApplication] setStatusBarStyle:[self preferredStatusBarStyle]];
    }
    [self rePositionViews];
    [super viewWillAppear:animated];
}
```

**Modify to supportedInterfaceOrientations method to**

```
- (NSUInteger)supportedInterfaceOrientations
{
    if ((self.orientationDelegate != nil) && [self.orientationDelegate respondsToSelector:@selector(supportedInterfaceOrientations)]) {
        CGRect viewBounds = [self.webView bounds];
            if (orgWidth == 0 && orgHeight == 0) { //set height and width on launch 
                if ([self hasTopNotch]) { //when app is launched in portrait mode, set hight excluding safe area
                    float topSafeArea = [[[UIApplication sharedApplication] delegate] window].safeAreaInsets.top;
                    orgHeight = viewBounds.size.height - (topSafeArea);
                    orgWidth = viewBounds.size.width;
                } else { //when app is launched in landscape mode, set width excluding safe area
                    float leftSafeArea = [[[UIApplication sharedApplication] delegate] window].safeAreaInsets.left;
                    orgHeight = viewBounds.size.height;
                    orgWidth = viewBounds.size.width - (2*leftSafeArea);
                }
            } else if ([self hasTopNotch] && viewRenderedAtLeastOnce) { //on oritentation change, swap dimensions assuming safe area
                float topSafeArea = [[[UIApplication sharedApplication] delegate] window].safeAreaInsets.top;
                viewBounds.origin.y = topSafeArea;
                if(viewBounds.size.height == orgWidth) { //this block is when landscape to portrait is changed
                    viewBounds.size.height = orgWidth;
                    viewBounds.size.width = orgHeight;
                } else {
                    viewBounds.size.height = orgHeight;
                    viewBounds.size.width = orgWidth;
                }
            } else if ([self hasLeftOrRightNotch] && viewRenderedAtLeastOnce) {
                float leftSafeArea = [[[UIApplication sharedApplication] delegate] window].safeAreaInsets.left;
                viewBounds.origin.x = leftSafeArea;
                if(viewBounds.size.width == orgHeight) { //this block is when portrait to landscape is changed
                    viewBounds.size.height = orgWidth;
                    viewBounds.size.width = orgHeight;
                } else {  // special case of oritention change from portrait to landscaoe both left and right direction
                    viewBounds.size.width = orgHeight - leftSafeArea;
                    viewBounds.size.height = orgWidth;
                }
            } else { //for non notched devices
                viewBounds.origin.y = STATUSBAR_HEIGHT;
                viewBounds.size.height = orgHeight;
            }
        self.webView.frame = viewBounds;
        [self rePositionViews];
        
        return [self.orientationDelegate supportedInterfaceOrientations];
    }
```

**Comment by NiklasMerz** [comment]
Should be solved with #604 which is the proper solution

**Pull request closed without merging**
