### PR TITLE
CB-13791: (android) Add Android support for a footer close button

### PR DESCRIPTION
**Pull request by dpa99c**
### Platforms affected
Android

### What does this PR do?
Adds support to Android for a footer close button similar to the "Done" button on iOS.

### What testing has been done on this change?
Manual testing as there's no currently no automated tests for platform-specific options.
I've tested all the possible combinations of the new `footer` and `footercolor` options with the related `closebuttoncaption` and `closebuttoncolor` options. The screenshots below illustrate the results:

`location=yes,footer=yes`

`location=no,footer=yes`

`location=yes,footer=yes,closebuttoncaption=Done`

`location=no,footer=yes,closebuttoncaption=Done,closebuttoncolor=#0000ff`

`location=no,footer=yes,footercolor=#0000ff,closebuttoncaption=Done`

`location=no,footer=yes,footercolor=#00ff00,closebuttoncaption=Done,closebuttoncolor=#0000ff`

`location=no,footer=yes,footercolor=#CC000000,closebuttoncaption=Done,closebuttoncolor=#00FFFF`

### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [x] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by guanyuan** [comment]
Hi, I want to confirm whether it's work on Android 7?
In our app, it does not work.

**Comment by guanyuan** [comment]
Hi @dpa99c , I want to ask if it works on Android 7?
In our app, it does not work on Huawei P9 EVA-AL10

**Comment by dpa99c** [comment]
I just cloned [cordova-plugin-inappbrowser-test](https://github.com/dpa99c/cordova-plugin-inappbrowser-test) and added some footer options and it seems to work fine in Android 7:
screenshot_1546951772

**Comment by guanyuan** [comment]
@dpa99c  Thanks for your reply.
I also have another question.
If the url is binary stream, can it be opened by inappbrowser for android?
In our app, IOS is ok, but Android only open a blank page.

If I get the url by postman, I can see that the content-type of  response header is something like:
Content-Type →application/octet-stream;charset=UTF-8

**Pull request merged**
