### PR TITLE
CB-10395 InAppBrowser's WebView not storing cookies reliable

### PR DESCRIPTION
**Pull request by sgrebnov**
https://issues.apache.org/jira/browse/CB-10395

### CODE REVIEW

**Comment by sgrebnov** [comment]
@wolframkriesing please review

**Comment by wolframkriesing** [comment]
hey cool that this is finding it's way.
Meanwhile we fixed the problem for older androids too, I updated the comment in  https://issues.apache.org/jira/browse/CB-10395 and the changed code is here https://github.com/crewmeister/cordova-plugin-inappbrowser/commit/5bf3542ded36803d2824aa53d0f7540778c113f2#diff-6b96481eda04f0b853d9e7b6637d167b

**Comment by sgrebnov** [comment]
pls review updated version

**Comment by wolframkriesing** [comment]
I think importing the `CookieSyncManager ` is missing

**Comment by sgrebnov** [comment]
Thx for review - updated, tested and merged

**Pull request closed without merging**
