### PR TITLE
[BREAKING] (all platforms): remove "window.open" overwrite

### LINKED ISSUE #599: Remove window.open overwrite
# Feature Request

## Motivation Behind Feature

Like described in the README file a long time ago there was a plan to remove the backwards compatibility of overwriting `window.open` in a future release. [See](WKWebViewOnly https://github.com/apache/cordova-plugin-inappbrowser#windowopen)

> For backwards compatibility, this plugin also hooks window.open. However, the plugin-installed hook of window.open can have unintended side effects (especially if this plugin is included only as a dependency of another plugin). The hook of window.open will be removed in a future major release. Until the hook is removed from the plugin, apps can manually restore the default behaviour:

## Feature Description

We should remove this overwrite of the native browser window function to avoid errors like this:

#315 
#403 

## Alternatives or Workarounds

A proposal to change the docs exists #528

### PR DESCRIPTION
**Pull request by NiklasMerz**
Closes #599

### Platforms affected
All

### Motivation and Context
See #599 

### Testing

Tested shortly with https://github.com/dpa99c/cordova-plugin-inappbrowser-test

### Checklist

- [x] I've run the tests to see all new and existing tests pass
- [x] I added automated test coverage as appropriate for this change -> **Some tests got stuck a first but restarting CI fixed that**
- [x] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [x] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [x] I've updated the documentation if necessary

### CODE REVIEW

**Comment by NiklasMerz** [comment]
Yes this is a breaking change intended for the next major release. I raised #599 to discuss this and make a decision when time has come for a major release.

If this is released we could check and possibly close the issues around `window.open`.

**Comment by brodybits** [comment]
Thanks. I think I cannot stress enough how important it is to make it absolutely clear if a PR contains a breaking change. While we should expect current InAppBrowser maintainers to pick this up, we have seen maintainers come and go due to external factors. (I can only imagine if another maintainer would just do LGTM, merge and release without realizing that this is a breaking change ... kaboom!)

It was certainly not clear to me from first glance in this PR and #599 that you wanted to discuss the next major release in #599.

That said, I just sent a proposal to the mailing list to do a version bump and get this PR reviewed & potentially merged. Thanks for your quick work on this.

**Comment by rpanadero** [comment]
I agree with @NiklasMerz, this change will fix many issues related to window.open overwrite side effects. I'm looking forward to seeing this PR merged in order to remove the hack I have in my application. Thanks.

**Comment by brodybits** [comment]
Maintainers are a bit overloaded. I would highly recommend that you follow up with us on the mailing list or on Slack, please follow the links in the footer of cordova.io or cordova.apache.org.

**Comment by NiklasMerz** [comment]
Next major version is work in progress right now. We can merge this once we get some review for this.

**We should not forget to mention this in the changelog and release blog post, since this is a breaking change**. I changed the title to make that the visible in the commit message.

**Comment by NiklasMerz** [comment]
Thanks @timbru31 and @erisu. Whenever 4.0.0 is prepared this should be merged.

**Comment by NiklasMerz** [comment]
@erisu Does this cover electron, too? Does electron use browser?

**Comment by timbru31** [comment]
What's the status on this, Niklas? Could you solve the electron question?
(AFAIK electron uses electron platform and browser as a fallback).

Given the fact that the master already contains breaking changes, we could merge this.

**Comment by NiklasMerz** [comment]
I think it's good to merge. As far as I can remember this should not affect electron.

**Comment by erisu** [comment]
It is OK in regards to Electron.

**Pull request merged**
