### PR TITLE
CB-12834: (android) Fix bug when opening a download link

### PR DESCRIPTION
**Pull request by MeirBon**
### Platforms affected
Android

### What does this PR do?
It adds a dialog to request permissions when a file is downloaded in the inappbrowser. I have committed the changes using the given format, original changes are from [this pull request](https://github.com/apache/cordova-plugin-inappbrowser/pull/201)

### What testing has been done on this change?
Multiple Android devices have been tested. Different download links, cancelling the download then re-downloading.

### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by cordova-qa** [comment]
Cordova CI Build has completed successfully.

**Commit**     - [Link](https://github.com/apache/cordova-plugin-inappbrowser/pull/221/commits/d246092d1a066160aa4f3a4e5424b255d1550076)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-inappbrowser-pr/145/)

 36 tests run, 0 skipped, 0 failed.

**Comment by alanhg** [comment]
Please publish the official version v1.7.2 as soon as possible.
I need to implement download file like pdf or doc .

**Comment by adirel** [comment]
I join this request.

**Comment by RafaelKr** [comment]
This is awesome!
But can you please change the function `processDownload` like this?

```Java
import android.webkit.CookieManager;

[...]

protected void processDownload() {
    final String url = InAppBrowserDownloads.this.url;
    final String cookie = CookieManager.getInstance().getCookie(url);
    final String filename = URLUtil.guessFileName(url, InAppBrowserDownloads.this.contentDisposition, InAppBrowserDownloads.this.mimetype);
    DownloadManager.Request request = new DownloadManager.Request(Uri.parse(url));

    request.addRequestHeader("Cookie", cookie);
    request.addRequestHeader("User-Agent", InAppBrowserDownloads.this.userAgent);
    request.addRequestHeader("Referer", url);
    request.allowScanningByMediaScanner();
    // Notify client once download is completed!
    request.setNotificationVisibility(DownloadManager.Request.VISIBILITY_VISIBLE_NOTIFY_COMPLETED);
    request.setDestinationInExternalPublicDir(Environment.DIRECTORY_DOWNLOADS, filename);

    try {
        DownloadManager dm = (DownloadManager) plugin.cordova.getActivity().getSystemService(DOWNLOAD_SERVICE);
        dm.enqueue(request);

        Intent intent = new Intent(Intent.ACTION_OPEN_DOCUMENT); // This is important!
        intent.addCategory(Intent.CATEGORY_OPENABLE); // CATEGORY.OPENABLE
        intent.setType("*/*"); // any application, any extension
        Toast.makeText(plugin.cordova.getActivity().getApplicationContext(), "Downloading File '" + filename + "'", Toast.LENGTH_LONG).show();
    } catch (Exception exception) {
        Toast.makeText(plugin.cordova.getActivity().getApplicationContext(), "Error downloading file, missing storage permissions", Toast.LENGTH_LONG).show();
        exception.printStackTrace();
    }
}
```

This passes the cookies from the WebView to the DownloadManager, so you're able to download files from locations where you need to be signed in.
I also cleaned up the code a little bit. The important code I added is this part:
```Java
import android.webkit.CookieManager;
[...]
final String cookie = CookieManager.getInstance().getCookie(url); // Note that I defined the variable url before
[...]
request.addRequestHeader("Cookie", cookie);
request.addRequestHeader("User-Agent", InAppBrowserDownloads.this.userAgent);
request.addRequestHeader("Referer", url);
[...]
```

**Comment by MeirBon** [comment]
@RafaelKr Don't have the time right now to work on this. Feel free to make a pull request to my fork and I will take a look when I have time.

**Comment by adirel** [comment]
@RafaelKr, Just wanted to let you know that we've tested your branch. Great work!

**Comment by adirel** [comment]
Hi @RafaelKr, Few points about old devices. 
the app crash whith error on line 109 at In: cordova-plugin-inappbrowser\www\inappbrowser.js 

**the code:** 

+      let windowFeatures = {
+        width: isNumeric(size.width) ? size.width : null,
+        height: isNumeric(size.height) ? size.height : null
+      };

**error recived:**
D/SystemWebChromeClient( 8784): file:///android_asset/www/plugins/cordova-plugin-inappbrowser/www/inappbrowser.js: Line 109 : Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

I/chromium( 8784): [INFO:CONSOLE(109)] "Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode", source: file:///android_asset/www/plugins/cordova-plugin-inappbrowser/www/inappbrowser.js (109)

**Comment by RafaelKr** [comment]
Hi @adirel, of course this `let` must be changed to `var`. Thank you!

**Comment by adirel** [comment]
Thank you. great work

**Comment by infil00p** [comment]
CRAP, this was a typo.  @RafaelKr can you re-open this one? I meant to close #201

**Comment by RafaelKr** [comment]
@infil00p I'm not the thread owner. @MeirBon could you please reopen this?

**Comment by MeirBon** [comment]
@RafaelKr I can't, the person that closed this issue or someone with push rights to this repo should be able to reopen it.

**Comment by infil00p** [comment]
@MeirBon Sadly, only asfgit has actual rights to this repo, since it's a mirror of the official repo.  I have to send empty-commits to close issues on this repo since it's only a mirror of the ASF repo and not official yet.  That is how the typo and this mistake happened.

I'll create a new branch, pull this in, and create a new PR to fix this screw-up.

**Comment by infil00p** [comment]
Continuing discussion on #244, I want to add this, but I think people are going to balk on adding the download permission for InAppBrowser.  However, since this is a compile-time option, and not a runtime option, it's not something you can easily create an option for in config.xml.

**Pull request closed without merging**
