### PR TITLE
CB-12266 browser: Fix type for InAppBrowserEvent url in docs

### PR DESCRIPTION
**Pull request by matrosov-nikita**
### Platforms affected
browser

### What does this PR do?
fix doc's description for URL

### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by cordova-qa** [comment]
Cordova CI Build has one or more failures. 

**Commit**     - [Link](https://github.com/apache/cordova-plugin-inappbrowser/pull/217/commits/6a93e34d459cd13ce74c9b01b595e242399ece16)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-inappbrowser-pr/137/)

 36 tests run, 0 skipped, 0 failed.

**Comment by alsorokin** [comment]
Let there be tests

**Comment by cordova-qa** [comment]
Cordova CI Build has one or more failures. 

**Commit**     - [Link](https://github.com/apache/cordova-plugin-inappbrowser/pull/217/commits/6a93e34d459cd13ce74c9b01b595e242399ece16)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-inappbrowser-pr/138/)

 36 tests run, 0 skipped, 0 failed.

**Comment by alsorokin** [comment]
Let there be tests

**Comment by cordova-qa** [comment]
Cordova CI Build has completed successfully.

**Commit**     - [Link](https://github.com/apache/cordova-plugin-inappbrowser/pull/217/commits/6a93e34d459cd13ce74c9b01b595e242399ece16)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-inappbrowser-pr/139/)

 42 tests run, 0 skipped, 0 failed.

**Comment by filmaj** [comment]
Please close this pull request - I have a PR to fix the underlying issue open over at #218.

**Pull request closed without merging**
